services:
  app:
    container_name: rrovixcon
#    image: rrovix:latest
    build:
      context: .
#     dockerfile: Dockerfile
      args:
      - user=${USER}
      - uid=${UIDI:-1000}
      - gid=${GIDI:-1000}

    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
# src to connect with X11 https://wiki.ros.org/docker/Tutorials/GUI#Using_Wayland
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.docker.xauth:/tmp/.docker.xauth:rw
      - ./cfg_docker_volume/:/opt/ros/overlay_ws/src/rovio/cfg/gopro10_docker
      - ./rosbags_docker_volume/:/opt/ros/overlay_ws/src/rovio/rosbags/gopro10_docker
    network_mode: host
#    command: source /opt/ros/overlay_ws/devel/setup.bash  && roslaunch rovio rovio_node.launch
