services:
  app:
    hostname: ros_rov
    container_name: rrovixcon
#    image: rrovix:latest
    build:
      context: .
#     dockerfile: Dockerfile
      args:
      - user=${USER}
      - uid=${UIDI:-1000}
      - gid=${GIDI:-1000}
    environment:
      - DISPLAY=${DISPLAY}
      - XAUTHORITY=/tmp/.docker.xauth
    deploy:
      resources:
        limits:
          cpus: '0.5' # Ограничение в потреблении ресурсов ЦПУ
    # src to connect with X11 https://wiki.ros.org/docker/Tutorials/GUI#Using_Wayland
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ./.docker.xauth:/tmp/.docker.xauth:rw
      - ./cfg_docker_volume/:/opt/ros/overlay_ws/src/rovio/cfg/gopro10_docker
      - ./rosbags_docker_volume/:/opt/ros/overlay_ws/src/rovio/rosbags/gopro10_docker
      - /dev/video0:/dev/video0 # Проброс устройства для обработки видео
      - /etc/localtime:/etc/localtime:ro # Монтирование настроек времени

    device_cgroup_rules:
      - 'c 81:* rmw' #Установка прав доступа к символьному устроййству основным номером 81:*
      #ls -l /dev/video0 узнать основной и младший номер устройства камеры
    network_mode: host

